version: '3'

services:
  hono-sample:
    build: .
    container_name: hono-sample
    volumes:
      - ../:/hono-sample
    networks:
      - hono-sample
    command: bash
    # stdin_open: true
    tty: true
    # restart: 'no'
    ports:
      - 3000:3000

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
    volumes:
      - ../db_data:/var/lib/posrgresql/data
      - ../initdb:/docker-entrypoint-initdb.d
    networks:
      - hono-sample

networks:
  hono-sample:
    external: true
    # driver: bridge

volumes:
  db_data: {}